// INSERT INTO hr_modules
//     (company_id, name, slug, icon, description, sort_order, is_active, is_system, created_at, updated_at)
// VALUES
//     (NULL, 'Employee', 'employee', '👤', 'Employee records and profile management', 1, 1, 1, NOW(), NOW())
// ON DUPLICATE KEY UPDATE updated_at = NOW();

// INSERT INTO form_definitions
//     (company_id, module_id, name, slug, description, sort_order, is_active, is_system, created_at, updated_at)
// VALUES
//     (NULL, @module_id, 'Employee Onboarding', 'employee_onboarding', 'Full employee onboarding wizard', 1, 1, 1, NOW(), NOW())
// ON DUPLICATE KEY UPDATE updated_at = NOW();

// INSERT INTO dynamic_fields
//     (company_id, form_id, field_type, label, field_key, section, sort_order, is_active, created_at, updated_at)
// VALUES
//     (1, 2, 'text', 'Employee Code', 'employee_code', 'Basic Info', 0, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Reference Code', 'reference_code', 'Basic Info', 1, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Company', 'company_id', 'Basic Info', 2, 1, NOW(), NOW()),
//     (1, 2, 'text', 'First Name', 'first_name', 'Basic Info', 3, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Middle Name', 'middle_name', 'Basic Info', 4, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Last Name', 'last_name', 'Basic Info', 5, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Status', 'status', 'Basic Info', 6, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Employment Type', 'employment_type', 'Basic Info', 7, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Email', 'email', 'Basic Info', 8, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Phone', 'phone', 'Basic Info', 9, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Department', 'department_id', 'Basic Info', 10, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Sub Department', 'sub_department_id', 'Basic Info', 11, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Designation', 'designation_id', 'Basic Info', 12, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Sub Designation', 'sub_designation', 'Basic Info', 13, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Avatar', 'avatar_url', 'Basic Info', 14, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Working Site', 'working_site', 'Employment Details', 15, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Working City', 'working_city', 'Employment Details', 16, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Working State/Country', 'working_state_country', 'Employment Details', 17, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Pay Register Location', 'pay_register_location', 'Employment Details', 18, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Saturday Off', 'saturday_off', 'Employment Details', 19, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Shift', 'shift_id', 'Employment Details', 20, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Grace Minutes', 'grace_minutes', 'Employment Details', 21, 1, NOW(), NOW()),
//     (1, 2, 'select', 'L1 Manager', 'l1_manager_id', 'Reporting & Contact', 22, 1, NOW(), NOW()),
//     (1, 2, 'select', 'L2 Manager', 'l2_manager_id', 'Reporting & Contact', 23, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Actual Date of Joining', 'actual_doj', 'Reporting & Contact', 24, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Current Date of Joining', 'current_doj', 'Reporting & Contact', 25, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Commitment', 'commitment', 'Commitment & Probation', 26, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Commitment Term', 'commitment_term', 'Commitment & Probation', 27, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Commitment Entered On', 'commitment_entered_on', 'Commitment & Probation', 28, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Commitment End Date', 'commitment_end_date', 'Commitment & Probation', 29, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Commitment Status', 'commitment_status', 'Commitment & Probation', 30, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'On Probation', 'on_probation', 'Commitment & Probation', 31, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Probation Period', 'probation_period', 'Commitment & Probation', 32, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Probation End Date', 'probation_end_date', 'Commitment & Probation', 33, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Probation Status', 'probation_status', 'Commitment & Probation', 34, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Probation Extended Period', 'probation_extended_period', 'Commitment & Probation', 35, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Probation Final Status', 'probation_final_status', 'Commitment & Probation', 36, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Confirmation Status', 'confirmation_status', 'Commitment & Probation', 37, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Confirmed On', 'confirmed_on', 'Commitment & Probation', 38, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'PF Status', 'pf_status', 'Schemes (PF/ESIC/Mediclaim/RD)', 39, 1, NOW(), NOW()),
//     (1, 2, 'text', 'UAN Number', 'uan_number', 'Schemes (PF/ESIC/Mediclaim/RD)', 40, 1, NOW(), NOW()),
//     (1, 2, 'text', 'EPFO Member ID', 'epfo_member_id', 'Schemes (PF/ESIC/Mediclaim/RD)', 41, 1, NOW(), NOW()),
//     (1, 2, 'number', 'PF Contribution %', 'pf_contribution_pct', 'Schemes (PF/ESIC/Mediclaim/RD)', 42, 1, NOW(), NOW()),
//     (1, 2, 'select', 'PF Employer From', 'pf_employer_from', 'Schemes (PF/ESIC/Mediclaim/RD)', 43, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'ESIC Status', 'esic_status', 'Schemes (PF/ESIC/Mediclaim/RD)', 44, 1, NOW(), NOW()),
//     (1, 2, 'text', 'ESIC Number', 'esic_number', 'Schemes (PF/ESIC/Mediclaim/RD)', 45, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Mediclaim Status', 'mediclaim_status', 'Schemes (PF/ESIC/Mediclaim/RD)', 46, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Mediclaim Number', 'mediclaim_number', 'Schemes (PF/ESIC/Mediclaim/RD)', 47, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Mediclaim Amount', 'mediclaim_amount', 'Schemes (PF/ESIC/Mediclaim/RD)', 48, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'RD Scheme', 'rd_scheme', 'Schemes (PF/ESIC/Mediclaim/RD)', 49, 1, NOW(), NOW()),
//     (1, 2, 'select', 'RD Term', 'rd_term', 'Schemes (PF/ESIC/Mediclaim/RD)', 50, 1, NOW(), NOW()),
//     (1, 2, 'date', 'RD Opening Date', 'rd_opening_date', 'Schemes (PF/ESIC/Mediclaim/RD)', 51, 1, NOW(), NOW()),
//     (1, 2, 'text', 'RD Account Number', 'rd_account_number', 'Schemes (PF/ESIC/Mediclaim/RD)', 52, 1, NOW(), NOW()),
//     (1, 2, 'select', 'RD Deduction From', 'rd_deduction_from', 'Schemes (PF/ESIC/Mediclaim/RD)', 53, 1, NOW(), NOW()),
//     (1, 2, 'number', 'RD Amount (Employee)', 'rd_amount_employee', 'Schemes (PF/ESIC/Mediclaim/RD)', 54, 1, NOW(), NOW()),
//     (1, 2, 'number', 'RD Amount (Employer)', 'rd_amount_employer', 'Schemes (PF/ESIC/Mediclaim/RD)', 55, 1, NOW(), NOW()),
//     (1, 2, 'date', 'RD Maturity Date', 'rd_maturity_date', 'Schemes (PF/ESIC/Mediclaim/RD)', 56, 1, NOW(), NOW()),
//     (1, 2, 'number', 'RD Maturity Amount', 'rd_maturity_amount', 'Schemes (PF/ESIC/Mediclaim/RD)', 57, 1, NOW(), NOW()),
//     (1, 2, 'text', 'RD Status', 'rd_status', 'Schemes (PF/ESIC/Mediclaim/RD)', 58, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Personal Email', 'personal_email', 'Personal', 59, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Personal Mobile', 'personal_mobile', 'Personal', 60, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Date of Birth', 'date_of_birth', 'Personal', 61, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Gender', 'gender', 'Personal', 62, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Blood Group', 'blood_group', 'Personal', 63, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Shirt Size', 'shirt_size', 'Personal', 64, 1, NOW(), NOW()),
//     (1, 2, 'select', 'T-Shirt Size', 'tshirt_size', 'Personal', 65, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Nationality', 'nationality', 'Personal', 66, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Religion', 'religion', 'Personal', 67, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Marital Status', 'marital_status', 'Personal', 68, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Marriage Date', 'marriage_date', 'Personal', 69, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Spouse Name', 'spouse_name', 'Personal', 70, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Spouse DOB', 'spouse_dob', 'Personal', 71, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Child 1 Name', 'child1_name', 'Personal', 72, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Child 1 DOB', 'child1_dob', 'Personal', 73, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Child 2 Name', 'child2_name', 'Personal', 74, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Child 2 DOB', 'child2_dob', 'Personal', 75, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Child 3 Name', 'child3_name', 'Personal', 76, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Child 3 DOB', 'child3_dob', 'Personal', 77, 1, NOW(), NOW()),
//     (1, 2, 'select', 'House Type', 'present_house_type', 'Address', 78, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present House No', 'present_house_no', 'Address', 79, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present Area', 'present_area', 'Address', 80, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present District', 'present_district', 'Address', 81, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present City', 'present_city', 'Address', 82, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present State', 'present_state', 'Address', 83, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present Country', 'present_country', 'Address', 84, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Present Pincode', 'present_pincode', 'Address', 85, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Permanent Address Type', 'perm_address_type', 'Address', 86, 1, NOW(), NOW()),
//     (1, 2, 'select', 'House Type', 'perm_house_type', 'Address', 87, 1, NOW(), NOW()),
//     (1, 2, 'text', 'House No', 'perm_house_no', 'Address', 88, 1, NOW(), NOW()),
//     (1, 2, 'text', 'District', 'perm_district', 'Address', 89, 1, NOW(), NOW()),
//     (1, 2, 'text', 'City', 'perm_city', 'Address', 90, 1, NOW(), NOW()),
//     (1, 2, 'text', 'State', 'perm_state', 'Address', 91, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Country', 'perm_country', 'Address', 92, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Pincode', 'perm_pincode', 'Address', 93, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Father Salutation', 'father_salutation', 'Family', 94, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Father Name', 'father_name', 'Family', 95, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Father Age/DOB', 'father_age_dob', 'Family', 96, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Father Occupation', 'father_occupation', 'Family', 97, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Father Status', 'father_status', 'Family', 98, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Mother Salutation', 'mother_salutation', 'Family', 99, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Mother Name', 'mother_name', 'Family', 100, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Mother Age/DOB', 'mother_age_dob', 'Family', 101, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Mother Occupation', 'mother_occupation', 'Family', 102, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Contact Name', 'contact_name', 'Emergency Contacts', 103, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Contact Number', 'contact_number', 'Emergency Contacts', 104, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Relationship', 'relationship', 'Emergency Contacts', 105, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Is Primary', 'is_primary', 'Emergency Contacts', 106, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Passport Number', 'passport_number', 'Statutory', 107, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Passport Expiry', 'passport_expiry', 'Statutory', 108, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Yellow Fever', 'yellow_fever', 'Statutory', 109, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Yellow Fever Date', 'yellow_fever_date', 'Statutory', 110, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Driving License Number', 'driving_license_number', 'Statutory', 111, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Driving License Expiry', 'driving_license_expiry', 'Statutory', 112, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Aadhaar Number', 'aadhaar_number', 'Statutory', 113, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Aadhaar Address', 'aadhaar_address', 'Statutory', 114, 1, NOW(), NOW()),
//     (1, 2, 'text', 'PAN Number', 'pan_number', 'Statutory', 115, 1, NOW(), NOW()),
//     (1, 2, 'text', 'PAN Full Name', 'pan_full_name', 'Statutory', 116, 1, NOW(), NOW()),
//     (1, 2, 'date', 'PAN DOB', 'pan_dob', 'Statutory', 117, 1, NOW(), NOW()),
//     (1, 2, 'text', 'PAN Parent/Spouse Name', 'pan_parent_spouse_name', 'Statutory', 118, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Bank Name', 'personal_bank_name', 'Bank Details', 119, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Account Number', 'personal_bank_account', 'Bank Details', 120, 1, NOW(), NOW()),
//     (1, 2, 'text', 'IFSC Code', 'personal_ifsc', 'Bank Details', 121, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Branch Name', 'personal_bank_branch', 'Bank Details', 122, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Official Bank Name', 'official_bank_name', 'Bank Details', 123, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Official Account Number', 'official_bank_account', 'Bank Details', 124, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Official IFSC Code', 'official_ifsc', 'Bank Details', 125, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Official Branch Name', 'official_bank_branch', 'Bank Details', 126, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Is Experienced', 'is_experienced', 'Experience', 127, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Last Company Name', 'last_company_name', 'Experience', 128, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Last Designation', 'last_designation', 'Experience', 129, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Last Working Day', 'last_working_day', 'Experience', 130, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Contact Name', 'exp_contact_name', 'Experience', 131, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Contact Number', 'exp_contact_number', 'Experience', 132, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Contact Designation', 'exp_contact_designation', 'Experience', 133, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Last In-hand Salary', 'last_inhand_salary', 'Experience', 134, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Highest Education', 'highest_education', 'Education', 135, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Education Stream', 'education_stream', 'Education', 136, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Education Mode', 'education_mode', 'Education', 137, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Institute Name', 'institute_name', 'Education', 138, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Passing Year', 'passing_year', 'Education', 139, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Education Marks', 'education_marks', 'Education', 140, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Salary Type', 'salary_type', 'Salary', 141, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Salary Mode', 'salary_mode', 'Salary', 142, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Basic', 'basic', 'Salary', 143, 1, NOW(), NOW()),
//     (1, 2, 'number', 'HRA', 'hra', 'Salary', 144, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Allowance 1', 'allowance1', 'Salary', 145, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Gross Salary (PM)', 'gross_salary_pm', 'Salary', 146, 1, NOW(), NOW()),
//     (1, 2, 'number', 'AMDB (PM)', 'amdb_pm', 'Salary', 147, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Total Earning (PM)', 'total_earning_pm', 'Salary', 148, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Effective From', 'effective_from', 'Salary', 149, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Applicable', 'asset_deduction_applicable', 'Asset Deduction', 150, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Security Amount', 'security_amount', 'Asset Deduction', 151, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Deduction Months', 'deduction_months', 'Asset Deduction', 152, 1, NOW(), NOW()),
//     (1, 2, 'select', 'Deduction From', 'deduction_from', 'Asset Deduction', 153, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Monthly Deduction', 'monthly_deduction', 'Asset Deduction', 154, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Last Installment', 'last_installment', 'Asset Deduction', 155, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Offer Letter', 'offer_letter', 'Onboarding Docs', 156, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Address Verification', 'address_verification', 'Onboarding Docs', 157, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Service Agreement', 'service_agreement', 'Onboarding Docs', 158, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Indemnity Bond', 'indemnity_bond', 'Onboarding Docs', 159, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Asset Deduction Letter', 'asset_deduction_letter', 'Onboarding Docs', 160, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Account Opening Letter', 'account_opening_letter', 'Onboarding Docs', 161, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'NDA', 'nda', 'Onboarding Docs', 162, 1, NOW(), NOW()),
//     (1, 2, 'number', 'Transfer Order', 'transfer_order', 'Transfers', 163, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Transferred On', 'transferred_on', 'Transfers', 164, 1, NOW(), NOW()),
//     (1, 2, 'text', 'New Company', 'new_company', 'Transfers', 165, 1, NOW(), NOW()),
//     (1, 2, 'date', 'New Joining Date', 'new_joining_date', 'Transfers', 166, 1, NOW(), NOW()),
//     (1, 2, 'text', 'New Location', 'new_location', 'Transfers', 167, 1, NOW(), NOW()),
//     (1, 2, 'text', 'New Department', 'new_department', 'Transfers', 168, 1, NOW(), NOW()),
//     (1, 2, 'text', 'New Job Title', 'new_job_title', 'Transfers', 169, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Old Company', 'old_company', 'Transfers', 170, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Exit Date', 'exit_date', 'Transfers', 171, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Old Location', 'old_location', 'Transfers', 172, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Old Department', 'old_department', 'Transfers', 173, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Old Job Title', 'old_job_title', 'Transfers', 174, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Old Employee Code', 'old_emp_code', 'Transfers', 175, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Resignation Submitted', 'resignation_submitted', 'Exit', 176, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Resignation Date', 'resignation_date', 'Exit', 177, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Notice Period', 'notice_period', 'Exit', 178, 1, NOW(), NOW()),
//     (1, 2, 'date', 'Last Working Day', 'exit_last_working_day', 'Exit', 179, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Exit Formalities Done', 'exit_formalities_done', 'Exit', 180, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Exit Status', 'exit_status', 'Exit', 181, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Exit Remarks', 'exit_remarks', 'Exit', 182, 1, NOW(), NOW()),
//     (1, 2, 'checkbox', 'Verified', 'verified', 'Exit', 183, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Verified By', 'verified_by', 'Exit', 184, 1, NOW(), NOW()),
//     (1, 2, 'text', 'Verification Remarks', 'verification_remarks', 'Exit', 185, 1, NOW(), NOW())
// ON DUPLICATE KEY UPDATE
//     label      = VALUES(label),
//     field_type = VALUES(field_type),
//     section    = VALUES(section),
//     sort_order = VALUES(sort_order),
//     is_active  = VALUES(is_active),
//     updated_at = NOW();