export const WIZARD_STEPS = [
  { key: 'basic',           label: 'Basic Info',             icon: 'user',         required: true,  sensitive: false },
  { key: 'employment',      label: 'Employment Details',     icon: 'briefcase',    required: true,  sensitive: false },
  { key: 'reporting',       label: 'Reporting & Contact',    icon: 'users',        required: true,  sensitive: false },
  { key: 'commitment',      label: 'Commitment & Probation', icon: 'calendar',     required: true,  sensitive: false },
  { key: 'schemes',         label: 'Enrolled Schemes',       icon: 'shield',       required: true,  sensitive: false },
  { key: 'personal',        label: 'Personal Details',       icon: 'heart',        required: true,  sensitive: false },
  { key: 'address',         label: 'Address',                icon: 'map-pin',      required: true,  sensitive: false },
  { key: 'family',          label: 'Family Details',         icon: 'users',        required: true,  sensitive: false },
  { key: 'emergency',       label: 'Emergency Contact',      icon: 'phone',        required: true,  sensitive: false },
  { key: 'statutory',       label: 'Documents & Govt IDs',   icon: 'file-text',    required: true,  sensitive: true  },
  { key: 'bank',            label: 'Bank Details',           icon: 'credit-card',  required: true,  sensitive: true  },
  { key: 'experience',      label: 'Experience & Education', icon: 'book',         required: true,  sensitive: false },
  { key: 'salary',          label: 'Salary & Deductions',    icon: 'indian-rupee', required: true,  sensitive: true  },
  { key: 'onboarding_docs', label: 'Onboarding Documents',   icon: 'check-square', required: true,  sensitive: false },
  { key: 'review',          label: 'Review & Submit',        icon: 'check-circle', required: true,  sensitive: false },
] as const;

export const EMPLOYEE_STATUS      = ['Active', 'Left', 'Retired'] as const;
export const EMPLOYMENT_TYPE      = ['Permanent', 'Contractual'] as const;
export const COMMITMENT_TERM      = ['36 Months', '60 Months', 'N/A'] as const;
export const CONFIRMATION_STATUS  = ['Confirmed', 'Failed', 'Not Applicable'] as const;
export const PF_EMPLOYER_FROM     = ['Employee', 'Employer', 'N/A'] as const;
export const MEDICLAIM_STATUS     = ['Yes', 'No', 'Deactivate'] as const;
export const PROBATION_PERIOD     = ['1 Month', '2 Months', '3 Months', '6 Months', '12 Months', 'N/A'] as const;
export const RD_TERM              = ['6 Months', '12 Months', '18 Months', '24 Months', '30 Months', '36 Months', 'N/A'] as const;
export const HOUSE_TYPE           = ['Own', 'Rent'] as const;
export const PERM_ADDRESS_TYPE    = ['Same as Present', 'Other'] as const;
export const FATHER_SALUTATION    = ['Mr.', 'Late'] as const;
export const MOTHER_SALUTATION    = ['Mrs.', 'Late'] as const;
export const PARENT_STATUS        = ['Working', 'Retired', 'Not Applicable'] as const;
export const MOTHER_STATUS        = ['Working', 'Retired', 'Not Applicable', 'House Wife'] as const;
export const SALARY_MODE          = ['Transfer', 'Cheque'] as const;
export const DEDUCTION_FROM       = ['Salary', 'AMDB', 'N/A'] as const;
export const DEDUCTION_MONTHS     = ['3 Months','6 Months','9 Months','12 Months','15 Months','18 Months','21 Months','24 Months','27 Months','30 Months','33 Months','36 Months','40 Months','N/A'] as const;
export const GENDER               = ['Male', 'Female', 'Other', 'Prefer not to say'] as const;
export const BLOOD_GROUP          = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] as const;
export const MARITAL_STATUS       = ['Single', 'Married', 'Divorced', 'Widowed', 'Separated'] as const;
export const AMDB_PERCENTAGE      = 0.30;

// Helper: convert constant arrays to Select options
export const toOpts = (arr: readonly string[]) => arr.map(v => ({ value: v, label: v }));

// ─── Static lookup lists (UNG CollarCheck master data) ───────────────────────
export const DEPARTMENT_OPTIONS = [
  { value: 1,  label: 'Commercial' },
  { value: 2,  label: 'Accounts' },
  { value: 3,  label: 'Automation' },
  { value: 4,  label: 'HR' },
  { value: 5,  label: 'Graphics' },
  { value: 6,  label: 'Admin' },
  { value: 7,  label: 'Project' },
  { value: 8,  label: 'Service' },
  { value: 9,  label: 'IT' },
  { value: 10, label: 'Estimation' },
  { value: 11, label: 'Management' },
  { value: 12, label: 'Purchase' },
  { value: 13, label: 'Tender' },
  { value: 14, label: 'Sales' },
  { value: 15, label: 'Technical' },
  { value: 16, label: 'Legal' },
  { value: 17, label: 'Regulatory Affairs' },
  { value: 18, label: 'Store' },
  { value: 19, label: 'Ortho' },
  { value: 20, label: 'Maintenance' },
  { value: 21, label: 'Design' },
  { value: 22, label: 'Quality' },
  { value: 23, label: 'Credit Control' },
  { value: 24, label: 'International Marketing' },
  { value: 25, label: 'Field' },
  { value: 26, label: 'Projects' },
  { value: 27, label: 'Facility Management (Operations)' },
  { value: 28, label: 'PTS and Project' },
  { value: 29, label: 'CSSD' },
  { value: 30, label: 'Quality Control' },
  { value: 31, label: 'Marketing' },
  { value: 32, label: 'Operations' },
] as const;

export const SUB_DEPARTMENT_OPTIONS = [
  { value: 1,  label: 'CSSD' },
  { value: 2,  label: 'MOT' },
  { value: 3,  label: 'Automation' },
  { value: 4,  label: 'NCS' },
  { value: 5,  label: 'PTS' },
  { value: 6,  label: 'Help Desk / IT Support' },
  { value: 7,  label: 'UI / UX / Frontend' },
  { value: 8,  label: 'PWLCS' },
  { value: 9,  label: 'Domestic' },
  { value: 10, label: 'Backend' },
  { value: 11, label: 'SEO' },
  { value: 12, label: 'International' },
  { value: 13, label: 'MGPS' },
  { value: 14, label: 'Whatsapp & Email' },
  { value: 15, label: 'Not Applicable' },
  { value: 16, label: 'Electrical' },
] as const;

export const DESIGNATION_OPTIONS = [
  { value: 1,  label: 'Accountant' },
  { value: 2,  label: 'Advisor' },
  { value: 3,  label: 'Asst. General Manager' },
  { value: 4,  label: 'Asst. Manager' },
  { value: 5,  label: 'CMD' },
  { value: 6,  label: 'Computer Operator' },
  { value: 7,  label: 'Cook' },
  { value: 8,  label: 'Coordinator' },
  { value: 9,  label: 'Deputy Manager' },
  { value: 10, label: 'Director' },
  { value: 11, label: 'Driver' },
  { value: 12, label: 'Electrician' },
  { value: 13, label: 'Engineer' },
  { value: 14, label: 'Executive' },
  { value: 15, label: 'Executive Assistant' },
  { value: 16, label: 'Field Assistant' },
  { value: 17, label: 'Fitter' },
  { value: 18, label: 'General Manager' },
  { value: 19, label: 'Guard' },
  { value: 20, label: 'Helper' },
  { value: 21, label: 'Jr. Accountant' },
  { value: 22, label: 'Jr. Executive' },
  { value: 23, label: 'Jr. Operator' },
  { value: 24, label: 'Jr. Technician' },
  { value: 25, label: 'Manager' },
  { value: 26, label: 'MIS Executive' },
  { value: 27, label: 'Office Attendant' },
  { value: 28, label: 'Operator' },
  { value: 29, label: 'Plumber' },
  { value: 30, label: 'Receptionist' },
  { value: 31, label: 'Sales Officer' },
  { value: 32, label: 'Senior Deputy Manager' },
  { value: 33, label: 'Site Engineer' },
  { value: 34, label: 'Sr. Computer Operator' },
  { value: 35, label: 'Sr. Coordinator' },
  { value: 36, label: 'Sr. Engineer' },
  { value: 37, label: 'Sr. Executive' },
  { value: 38, label: 'Sr. Field Assistant' },
  { value: 39, label: 'Sr. Fitter' },
  { value: 40, label: 'Sr. Helper' },
  { value: 41, label: 'Sr. Manager' },
  { value: 42, label: 'Sr. MIS Executive' },
  { value: 43, label: 'Sr. Sales Officer' },
  { value: 44, label: 'Supervisor' },
  { value: 45, label: 'Technician' },
  { value: 46, label: 'Data Entry Operator' },
  { value: 47, label: 'Security Guard' },
  { value: 48, label: 'Field Executive' },
  { value: 49, label: 'Site Supervisor' },
  { value: 50, label: 'Housekeeper' },
  { value: 51, label: 'Jr. Engineer' },
  { value: 52, label: 'Semi Fitter' },
  { value: 53, label: 'Sr. Developer' },
  { value: 54, label: 'Vice President' },
  { value: 55, label: 'Social Media Video Editor' },
  { value: 56, label: 'Quality Assurance Engineer' },
  { value: 57, label: 'Recruiter' },
  { value: 58, label: 'Sr. Site Engineer' },
  { value: 59, label: 'Jr. Site Engineer' },
  { value: 60, label: 'Site Manager' },
  { value: 61, label: 'Flutter Developer' },
  { value: 62, label: 'Incharge' },
  { value: 63, label: 'Sr. Recruiter' },
  { value: 64, label: 'Jr. Recruiter' },
  { value: 65, label: 'PSO' },
  { value: 66, label: 'Social Media Manager' },
  { value: 67, label: 'Fullstack Developer' },
  { value: 68, label: 'Software Engineer' },
  { value: 69, label: 'Dispatch Clerk Cum Engineer' },
  { value: 70, label: 'Jr. Fitter' },
  { value: 71, label: 'Deputy General Manager' },
  { value: 72, label: 'Jr. Electrician' },
  { value: 73, label: 'Social Media Executive' },
  { value: 74, label: 'Sr. Data Analyst' },
  { value: 75, label: 'Sr. Supervisor' },
  { value: 76, label: 'Sr. Software Engineer' },
] as const;

export const WORKING_SITE_OPTIONS = [
  { label: 'Head Office', value: 'Head Office' },
  { label: 'SIC', value: 'SIC' },
  { label: 'RML Hospital', value: 'RML Hospital' },
  { label: 'LBS Hospital', value: 'LBS Hospital' },
  { label: 'LNJP Hospital', value: 'LNJP Hospital' },
  { label: 'AIIMS Bhatinda', value: 'AIIMS Bhatinda' },
  { label: 'AIIMS Manglagiri', value: 'AIIMS Manglagiri' },
  { label: 'AIIMS Nagpur', value: 'AIIMS Nagpur' },
  { label: 'GMC Ratlam', value: 'GMC Ratlam' },
  { label: 'Warehouse', value: 'Warehouse' },
  { label: 'AIIMS Bilaspur', value: 'AIIMS Bilaspur' },
  { label: 'GMC Bhopal', value: 'GMC Bhopal' },
  { label: 'AIIMS Delhi', value: 'AIIMS Delhi' },
  { label: 'CNCI Kolkata', value: 'CNCI Kolkata' },
  { label: 'Marwad Daman', value: 'Marwad Daman' },
  { label: 'GMC Chapra', value: 'GMC Chapra' },
  { label: 'NIUM', value: 'NIUM' },
  { label: 'AIIMS Deoghar', value: 'AIIMS Deoghar' },
  { label: 'SKMCH', value: 'SKMCH' },
  {
    label: 'SCB Medical College And Hospital',
    value: 'SCB Medical College And Hospital',
  },
  { label: 'Victoria Hospital', value: 'Victoria Hospital' },
  { label: 'Amrita Hospital', value: 'Amrita Hospital' },
  {
    label: 'Acharya Shree Bhikshu Hospital',
    value: 'Acharya Shree Bhikshu Hospital',
  },
  { label: 'Central Vista', value: 'Central Vista' },
  { label: 'PGIMER Una', value: 'PGIMER Una' },
  { label: 'SMS Hospital', value: 'SMS Hospital' },
  { label: 'Bawana', value: 'Bawana' },
  { label: 'A4 Moti Bagh', value: 'A4 Moti Bagh' },
  { label: 'UMCH Dhaka', value: 'UMCH Dhaka' },
  {
    label: 'Maharaja Agrasen Hospital',
    value: 'Maharaja Agrasen Hospital',
  },
  { label: 'NA 45', value: 'NA 45' },
  { label: 'BDD Chawl', value: 'BDD Chawl' },
  {
    label: 'SCTIMST Thiruvananthapuram',
    value: 'SCTIMST Thiruvananthapuram',
  },
] as const;

export const WORKING_CITY_OPTIONS = [
  { label: 'New Delhi', value: 'New Delhi' },
  { label: 'Mumbai', value: 'Mumbai' },
  { label: 'Una', value: 'Una' },
  { label: 'Jaipur', value: 'Jaipur' },
  { label: 'Bhatinda', value: 'Bhatinda' },
  { label: 'Bilaspur', value: 'Bilaspur' },
  { label: 'Deoghar', value: 'Deoghar' },
  { label: 'Guntur', value: 'Guntur' },
  { label: 'Nagpur', value: 'Nagpur' },
  { label: 'Faridabad', value: 'Faridabad' },
  { label: 'Kolkata', value: 'Kolkata' },
  { label: 'Bhopal', value: 'Bhopal' },
  { label: 'Chapra', value: 'Chapra' },
  { label: 'Ratlam', value: 'Ratlam' },
  { label: 'Daman', value: 'Daman' },
  { label: 'Ghaziabad', value: 'Ghaziabad' },
  { label: 'Cuttack', value: 'Cuttack' },
  { label: 'Muzaffarpur', value: 'Muzaffarpur' },
  { label: 'Bangalore', value: 'Bangalore' },
  { label: 'Dhaka', value: 'Dhaka' },
  { label: 'Bahadurgarh', value: 'Bahadurgarh' },
  { label: 'Thiruvananthapuram', value: 'Thiruvananthapuram' },
] as const;

export const WORKING_STATE_COUNTRY_OPTIONS = [
  { label: 'Andaman & Nicobar, India', value: 'Andaman & Nicobar, India' },
  { label: 'Andhra Pradesh, India', value: 'Andhra Pradesh, India' },
  { label: 'Arunachal Pradesh, India', value: 'Arunachal Pradesh, India' },
  { label: 'Assam, India', value: 'Assam, India' },
  { label: 'Bihar, India', value: 'Bihar, India' },
  { label: 'Chandigarh, India', value: 'Chandigarh, India' },
  { label: 'Chhattisgarh, India', value: 'Chhattisgarh, India' },
  { label: 'Delhi, India', value: 'Delhi, India' },
  { label: 'Goa, India', value: 'Goa, India' },
  { label: 'Gujarat, India', value: 'Gujarat, India' },
  { label: 'Haryana, India', value: 'Haryana, India' },
  { label: 'Himachal Pradesh, India', value: 'Himachal Pradesh, India' },
  { label: 'Jammu & Kashmir, India', value: 'Jammu & Kashmir, India' },
  { label: 'Jharkhand, India', value: 'Jharkhand, India' },
  { label: 'Karnataka, India', value: 'Karnataka, India' },
  { label: 'Kerala, India', value: 'Kerala, India' },
  { label: 'Madhya Pradesh, India', value: 'Madhya Pradesh, India' },
  { label: 'Maharashtra, India', value: 'Maharashtra, India' },
  { label: 'Manipur, India', value: 'Manipur, India' },
  { label: 'Meghalaya, India', value: 'Meghalaya, India' },
  { label: 'Mizoram, India', value: 'Mizoram, India' },
  { label: 'Nagaland, India', value: 'Nagaland, India' },
  { label: 'Odisha, India', value: 'Odisha, India' },
  { label: 'Puducherry, India', value: 'Puducherry, India' },
  { label: 'Punjab, India', value: 'Punjab, India' },
  { label: 'Rajasthan, India', value: 'Rajasthan, India' },
  { label: 'Sikkim, India', value: 'Sikkim, India' },
  { label: 'Tamil Nadu, India', value: 'Tamil Nadu, India' },
  { label: 'Telangana, India', value: 'Telangana, India' },
  { label: 'Tripura, India', value: 'Tripura, India' },
  { label: 'Uttar Pradesh, India', value: 'Uttar Pradesh, India' },
  { label: 'Uttarakhand, India', value: 'Uttarakhand, India' },
  { label: 'West Bengal, India', value: 'West Bengal, India' },
  {
    label: 'Dadra and Nagar Haveli and Daman and Diu, India',
    value: 'Dadra and Nagar Haveli and Daman and Diu, India',
  },
  { label: 'Dhaka, Bangladesh', value: 'Dhaka, Bangladesh' },
] as const;


export const REGISTRATION_LOCATION_OPTIONS = [
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Haryana', value: 'Haryana' },
  { label: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { label: 'Ratlam, Madhya Pradesh', value: 'Ratlam, Madhya Pradesh' },
  { label: 'Chhindwara, Madhya Pradesh', value: 'Chhindwara, Madhya Pradesh' },
  { label: 'Vidisha, Madhya Pradesh', value: 'Vidisha, Madhya Pradesh' },
  { label: 'Bihar', value: 'Bihar' },
  { label: 'Khandwa, Madhya Pradesh', value: 'Khandwa, Madhya Pradesh' },
  { label: 'Almora, Uttarakhand', value: 'Almora, Uttarakhand' },
  { label: 'Daman, Gujarat', value: 'Daman, Gujarat' },
  { label: 'CNCI Kolkata', value: 'CNCI Kolkata' },
  { label: 'Bilaspur', value: 'Bilaspur' },
  { label: 'Gujarat', value: 'Gujarat' },
  { label: 'Bathinda', value: 'Bathinda' },
  { label: 'Mangalagiri', value: 'Mangalagiri' },
  { label: 'Jharkhand', value: 'Jharkhand' },
  { label: 'Nagpur, Mumbai', value: 'Nagpur, Mumbai' },
  { label: 'Telangana', value: 'Telangana' },
  { label: 'Una, Himachal Pradesh', value: 'Una, Himachal Pradesh' },
  { label: 'Kerala', value: 'Kerala' },
] as const;

export const SATURDAY_OFF_OPTIONS = [
  { label: '1st', value: '1st' },
  { label: '2nd', value: '2nd' },
  { label: '3rd', value: '3rd' },
  { label: '4th', value: '4th' },
  { label: '5th', value: '5th' },
  { label: '1st & 3rd', value: '1st & 3rd' },
  { label: '2nd & 4th', value: '2nd & 4th' },
  { label: '1st & 4th', value: '1st & 4th' },
  { label: '2nd & 3rd', value: '2nd & 3rd' },
  { label: '3rd & 4th', value: '3rd & 4th' },
  { label: '1st & 2nd', value: '1st & 2nd' },
  { label: '1st, 2nd & 3rd', value: '1st, 2nd & 3rd' },
  { label: '1st, 2nd & 4th', value: '1st, 2nd & 4th' },
  { label: '1st, 3rd & 4th', value: '1st, 3rd & 4th' },
  { label: '2nd, 3rd & 4th', value: '2nd, 3rd & 4th' },
  { label: 'All 4 Saturdays', value: 'All 4 Saturdays' },
  { label: 'All Saturdays', value: 'All Saturdays' },
  { label: 'No Saturday Off', value: 'No Saturday Off' },
] as const;

export const SHIFT_TIMING_OPTIONS = [
  { label: 'Shift (7.0 A - 3.0 P)', value: 1 },
  { label: 'Shift (8.0 A - 2.0 P)', value: 2 },
  { label: 'Shift (8.0 A - 4.3 P)', value: 3 },
  { label: 'Shift (8.0 A - 5.0 P)', value: 4 },
  { label: 'Shift (9.0 A - 5.3 P)', value: 5 },
  { label: 'Shift (9.0 A - 6.0 P)', value: 6 },
  { label: 'Shift (9.0 A - 7.0 P)', value: 7 },
  { label: 'Shift (9.15 A - 7.0 P)', value: 8 },
  { label: 'Shift (10.0 A - 6.0 P)', value: 9 },
  { label: 'Shift (10.0 A - 6.3 P)', value: 10 },
  { label: 'Shift (10.0 A -7.0 P)', value: 11 },
  { label: 'Shift (10.3 A - 7.3 P)', value: 12 },
  { label: 'Shift (11.0 A - 7.0 P)', value: 13 },
  { label: 'Shift (11.0 A - 8.0 P)', value: 14 },
  { label: 'Shift (11.3 A - 8.0 P)', value: 15 },
  { label: 'Shift (12.3 P - 9.0 P)', value: 16 },
  { label: 'Shift (1.0 P - 9.0 P)', value: 17 },
  { label: 'Shift (1.0 P - 9.3 P)', value: 18 },
  { label: 'Shift (2.0 P - 8.0 P)', value: 19 },
  { label: 'Shift (2.0 P - 9.0 P)', value: 20 },
  { label: 'Shift (2.0 P - 10.0 P)', value: 21 },
  { label: 'Shift (3.0 P - 11.0 P)', value: 22 },
  { label: 'Shift (5.0 P - 9.0 A)', value: 23 },
  { label: 'Shift (8.0 P - 6.0 A)', value: 24 },
  { label: 'Shift (8.0 P - 8.0 A)', value: 25 },
  { label: 'Shift (9.0 P - 5.3 A)', value: 26 },
  { label: 'Shift (11.0 P - 7.0 A)', value: 27 },

  { label: 'NAT (7.0 A - 3.0 P)', value: 28 },
  { label: 'NAT (8.0 A - 2.0 P)', value: 29 },
  { label: 'NAT (8.0 A - 4.3 P)', value: 30 },
  { label: 'NAT (8.0 A - 5.0 P)', value: 31 },
  { label: 'NAT (9.0 A - 5.3 P)', value: 32 },
  { label: 'NAT (9.0 A - 6.0 P)', value: 33 },
  { label: 'NAT (9.0 A - 7.0 P)', value: 34 },
  { label: 'NAT (9.15 A - 7.0 P)', value: 35 },
  { label: 'NAT (10.0 A - 6.0 P)', value: 36 },
  { label: 'NAT (10.0 A - 6.3 P)', value: 37 },
  { label: 'NAT (10.0 A -7.0 P)', value: 38 },
  { label: 'NAT (10.3 A - 7.3 P)', value: 39 },
  { label: 'NAT (11.0 A - 7.0 P)', value: 40 },
  { label: 'NAT (11.0 A - 8.0 P)', value: 41 },
  { label: 'NAT (11.3 A - 8.0 P)', value: 42 },
  { label: 'NAT (12.3 P - 9.0 P)', value: 43 },
  { label: 'NAT (1.0 P - 9.0 P)', value: 44 },
  { label: 'NAT (1.0 P - 9.3 P)', value: 45 },
  { label: 'NAT (2.0 P - 8.0 P)', value: 46 },
  { label: 'NAT (2.0 P - 9.0 P)', value: 47 },
  { label: 'NAT (2.0 P - 10.0 P)', value: 48 },
  { label: 'NAT (3.0 P - 11.0 P)', value: 49 },
  { label: 'NAT (5.0 P - 9.0 A)', value: 50 },
  { label: 'NAT (8.0 P - 6.0 A)', value: 51 },
  { label: 'NAT (8.0 P - 8.0 A)', value: 52 },
  { label: 'NAT (9.0 P - 5.3 A)', value: 53 },
  { label: 'NAT (11.0 P - 7.0 A)', value: 54 },

  { label: 'NAT (7.0 A - 5.0 P)', value: 55 },
  { label: 'Shift (7.0 A - 5.0 P)', value: 56 },
  { label: 'NAT (9.45 A - 7.0 P)', value: 57 },
  { label: 'Shift (9.45 A - 7.0 P)', value: 58 },
  { label: 'Shift (9.0 A - 9.0 P)', value: 59 },
  { label: 'NAT (9.0 A - 9.0 P)', value: 60 },
  { label: 'Shift (9.0 A - 5.0 P)', value: 61 },
  { label: 'NAT (9.0 A - 5.0 P)', value: 62 },
  { label: 'Shift (12.0 P - 8.0 P)', value: 63 },
  { label: 'NAT (12.0 P - 8.0 P)', value: 64 },
] as const;